# Generated by Django 3.2.5 on 2021-09-09 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='comandato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.TextField(default='SOME STRING')),
                ('titulo', models.TextField()),
                ('descripcion', models.TextField()),
                ('imagen', models.TextField()),
                ('precio', models.TextField()),
                ('link', models.CharField(default='SOME STRING', max_length=250)),
                ('fecha', models.CharField(default='SOME STRING', max_length=250)),
            ],
        ),
    ]
