# Generated by Django 3.2.5 on 2021-09-02 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercadoLibre', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mercadolibre',
            name='codigo',
            field=models.CharField(default='SOME STRING', max_length=250),
        ),
    ]
