# Generated by Django 3.2.5 on 2021-09-02 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mercadoLibre', '0002_mercadolibre_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mercadolibre',
            name='codigo',
        ),
    ]
