# Generated by Django 3.2.5 on 2021-09-02 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercadoLibre', '0003_remove_mercadolibre_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='mercadolibre',
            name='codigo',
            field=models.CharField(default='SOME STRING', max_length=250),
        ),
    ]
