# Generated by Django 3.2.5 on 2021-09-02 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mercadoLibre', '0004_mercadolibre_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mercadolibre',
            name='codigo',
        ),
    ]
