# Generated by Django 3.2.5 on 2021-09-04 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercadoLibre', '0006_auto_20210904_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='mercadolibre',
            name='link',
            field=models.CharField(default='SOME STRING', max_length=250),
        ),
    ]
