# Generated by Django 3.2.5 on 2021-09-06 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercadoLibre', '0007_mercadolibre_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='mercadolibre',
            name='fecha',
            field=models.CharField(default='SOME STRING', max_length=250),
        ),
    ]
