# Generated by Django 3.2.5 on 2021-09-09 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mercadoLibre', '0009_auto_20210908_1534'),
        ('mercadoLibre', '0009_mercadolibre_codigo'),
    ]

    operations = [
    ]
