# Generated by Django 3.2.5 on 2021-07-23 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='coderegister',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='user',
            name='coderegister',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
